Migrate to package-based build, add custom debug settings
zed-0xff/RW-YADA pull request #1
Opened 2023-05-06 07:33 UTC by oorzkws

This PR does two things:

- Cleans up the build process
  - Migrates from a reference to a local RimWorld install to the Krafs.Rimworld.Ref package
  - Drops the `net472` from the output path, no more moves needed
    - **This will need your eyes on the [rakefile](https://github.com/zed-0xff/RW-YADA/blob/ba8d1c4c31a1eb6eaf57ff3607d1ce01f0a1f5d8/Rakefile#L9), as I'm not sure if the syntax changes now that there's no subdirectory in `/Assemblies`**
- Implements the ability to add custom debug (development mode) settings
  - Adds two new settings:
    - `disableAutomaticUndraft` - Disables automatic undrafting of drafted-but-idle pawns
    - `freezeNeedsAtMaximum` - Prevents pawn needs from decreasing below the maximum value
  - Includes a simple framework for adding new settings
  
There's also just minor cleanup by removing unused `using` directives, as I wanted to refactor them after my own changes. Since your gitignore excludes dll files, I've attached the built dll of the PR branch [here](https://github.com/zed-0xff/RW-YADA/files/11411776/YADA.dll.gz).

2023-05-06 07:34 UTC, oorzkws commented
Ah, I forgot to mention - it would be appreciated if you choose and include a license for your project so I know what kind of changes I can make, and where I can keep or share them.

2023-05-06 19:23 UTC, zed-0xff requested changes

2023-05-06 19:23 UTC, zed-0xff commented on Source/Folder.DotSettings.user
pls remove this file

2023-05-06 19:23 UTC, zed-0xff commented on Source/YADA.csproj.DotSettings
and this one

2023-05-06 21:04 UTC, oorzkws commented
Done. I had forgotten dotsettings was rider-specific.

2023-05-12 10:12 UTC, zed-0xff commented
@oorzkws could you please resolve conflicts?

PS license added

2023-05-12 12:13 UTC, merged